modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/Towdium/JustEnoughCharacters/issues"
license = "The MIT License (MIT)"

[[mods]]
modId = "jecharacters"
version = "${version}"
displayName = "Just Enough Characters"
displayURL = "https://github.com/Towdium/JustEnoughCharacters"
credits = "Thanks to TartaricAcid, 3TUSK, Seraph_JACK, Snownee and many people for their efforts for development of the Chinese modding community."
authors = "Towdium, yzl210, Death-123, vfyjxf_"
description = "Pinyin search for JEI and more."

[[dependencies.jecharacters]]
modId = "forge"
mandatory = true
versionRange = "[36.2.41,)"
ordering = "AFTER"
side = "CLIENT"
